version: '3.7'

name: "chatbot"

services:
  rasa-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rasa
      network: host
    container_name: rasa-service
    restart: unless-stopped
    env_file: .env.development
    networks:
      - chatbot_default
    volumes:
      - ../app:/rasa/app
      - ../extensions:/rasa/extensions
      - ../config:/rasa/config
      - ../tmp:/rasa/tmp
    ports:
      - 8002:8002

networks:
  chatbot_default:
    name: chatbot_default
    driver: bridge
  host:
    name: host
    external: true
