version: "3.7"

name: "chatbot"

services:
  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - "./data:/data"
    command: server --address ":9099" --console-address ":9000" /data
    restart: always # necessary since it's failing to start sometimes

# x-minio-common: &minio-common
#   image: minio/minio:RELEASE.2020-04-28T23-56-56Z
#   command: server ":${MINIO_CLI_DEFAULT_PORT}" http://minio{1...2}/data{1...2}
#   restart: unless-stopped
#   expose:
#     - "${MINIO_DEFAULT_PORT}"
#     - "${MINIO_CLI_DEFAULT_PORT}"
#   environment:
#     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#   healthcheck:
#     test:
#       [
#         "CMD",
#         "curl",
#         "-f",
#         "http://localhost:${MINIO_DEFAULT_PORT}/minio/health/live",
#       ]
#     interval: 30s
#     timeout: 20s
#     retries: 3

# services:
#   minio1:
#     <<: *minio-common
#     hostname: minio1
#     volumes:
#       - "${DISK_PATH}/data-1-1:/data1"
#       - "${DISK_PATH}/data-1-2:/data2"
#     networks:
#       - chatbot_default

#   minio2:
#     <<: *minio-common
#     hostname: minio2
#     volumes:
#       - "${DISK_PATH}/data-2-1:/data1"
#       - "${DISK_PATH}/data-2-2:/data2"
#     networks:
#       - chatbot_default

#   nginx:
#     image: nginx:1.23.1-alpine
#     hostname: nginx
#     restart: unless-stopped
#     ports:
#       - "${MINIO_OS_PORT}:${MINIO_DEFAULT_PORT}"
#       - "${MINIO_CLI_OS_PORT}:${MINIO_CLI_DEFAULT_PORT}"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - minio1
#       - minio2
#     networks:
#       - chatbot_default

# networks:
#   chatbot_default:
#     driver: bridge
#     external: true
