version: '3.7'

name: "chatbot"

services:
  postgresdb:
    image: postgres:14.4-alpine
    container_name: chatbot-database
    restart: unless-stopped
    env_file: .env.database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 8025:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres-data:
    driver: local
